# Inspired by :
# https://github.com/astropy/ci-helpers/blob/master/.travis.yml
# And:
# https://github.com/Becksteinlab/GromacsWrapper/blob/master/.travis.yml

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

os:
  - linux
  - osx

sudo: false

git:
  depth: false

branches:
  only:
    - master

env:
  global:
    - PYTHON_VERSION=3.6
    - PIP_DEPENDENCIES="pytest==5.2.2 codecov pytest-cov"

cache: pip

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.5
        - os: osx
          env: PYTHON_VERSION=3.7

install:
  - pip install -r requirements.txt

script:
  - cd ${TRAVIS_BUILD_DIR}
  # Test os_command_py
  # Need to add --ignore to avoid weird error, see: https://github.com/pytest-dev/pytest/issues/4782
  - pytest --ignore ci-helpers --cov-report=xml --cov=os_command_py
  # Build Doc:
  - cd os_command_py/doc
  - sphinx-build -b html . _build

after_success:
  # Launch pytest for codecov
  - cd ${TRAVIS_BUILD_DIR}
  - codecov