language: python

python:
  - "3.5"
  - "3.7"

os:
  - linux
  - osx

sudo: false

git:
  depth: false

branches:
  only:
    - master

cache: pip

install:
  - pip install -r requirements.txt

script:
  - cd ${TRAVIS_BUILD_DIR}
  # Test os_command_py
  # Need to add --ignore to avoid weird error, see: https://github.com/pytest-dev/pytest/issues/4782
  - pytest --ignore ci-helpers --cov-report=xml --cov=os_command_py
  # Build Doc:
  - cd os_command_py/doc
  - sphinx-build -b html . _build

after_success:
  # Launch pytest for codecov
  - cd ${TRAVIS_BUILD_DIR}
  - codecov